name: Continuous Integration

on:
  push:
    branches:
      - main
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-test-${{ hashFiles('foo/go.sum') }}
          restore-keys: |
            go-test-${{ hashFiles('foo/go.sum') }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: foo/go.mod
          check-latest: true
          cache-dependency-path: foo/go.sum

      - run: go test -race --cover ./...
        working-directory: foo

