name: Continuous Integration

on:
  push:
    branches:
      - main
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: foo/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: foo/go.sum

      - run: go test ./...
        working-directory: foo
