name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        if: ${{ steps.filter.outputs.changed == 'true' }}
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - run: go test -v foo
      - run: go test -v bar