name: Continuous Integration

on:
  push:
    branches:
      - main
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: '1.20'
          check-latest: true
          cache: true
          cache-dependency-path: go.work.sum

      - run: go test -v -race -coverprofile=coverage.out -vet=off -timeout 20m foo
